package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"siptunnel/internal/config"
)

type configSource string

const (
	configSourceCLI              configSource = "cli"
	configSourceEnv              configSource = "env"
	configSourceExeDir           configSource = "exe_dir"
	configSourceCWD              configSource = "cwd"
	configSourceDefaultGenerated configSource = "default_generated"
)

type configCandidate struct {
	path   string
	source configSource
}

type configLoadResult struct {
	Path            string
	Source          configSource
	AutoGenerated   bool
	GeneratedAsMode string
	Candidates      []string
}

func readCLIConfigPath(args []string) (string, error) {
	fs := flag.NewFlagSet("gateway", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	configPath := fs.String("config", "", "gateway config file path")
	if err := fs.Parse(args); err != nil {
		return "", err
	}
	return strings.TrimSpace(*configPath), nil
}

func handleConfigCommands(args []string) (bool, error) {
	cmd, cmdArgs, ok := extractToolCommand(args)
	if !ok {
		return false, nil
	}
	switch cmd {
	case "init-config":
		cliPath, err := readCLIConfigPath(cmdArgs)
		if err != nil {
			return true, err
		}
		path := resolveConfigOutputPath(cliPath, os.Getenv("GATEWAY_CONFIG"), os.Getwd, os.Executable, runtime.GOOS)
		created, err := writeConfigIfNotExists(path, false)
		if err != nil {
			return true, err
		}
		if created {
			log.Printf("config initialized path=%q next_step=%q", path, "edit config then run gateway.exe --config <path>")
		} else {
			log.Printf("config already exists path=%q next_step=%q", path, "use print-default-config to view defaults")
		}
		if err := config.LoadStoragePathsFromEnv().EnsureWritable(); err != nil {
			return true, err
		}
		return true, nil
	case "print-default-config":
		b, err := defaultConfigYAML(runtime.GOOS)
		if err != nil {
			return true, err
		}
		fmt.Print(string(b))
		return true, nil
	case "validate-config":
		fs := flag.NewFlagSet("validate-config", flag.ContinueOnError)
		cfgPath := fs.String("f", "", "config file path")
		fs.SetOutput(os.Stderr)
		if err := fs.Parse(cmdArgs); err != nil {
			return true, err
		}
		if strings.TrimSpace(*cfgPath) == "" {
			return true, errors.New("validate-config requires -f <path>")
		}
		data, err := os.ReadFile(strings.TrimSpace(*cfgPath))
		if err != nil {
			return true, err
		}
		runtimeCfg, err := parseRuntimeConfigFromTopLevelYAML(data)
		if err != nil {
			return true, err
		}
		if err := runtimeCfg.Network.Validate(); err != nil {
			return true, err
		}
		if err := runtimeCfg.UI.Validate(); err != nil {
			return true, err
		}
		if err := config.LoadStoragePathsFromEnv().EnsureWritable(); err != nil {
			return true, err
		}
		log.Printf("config validation passed path=%q next_step=%q", *cfgPath, "start gateway with --config <path>")
		return true, nil
	default:
		return false, nil
	}
}

type runtimeConfig struct {
	Network config.NetworkConfig
	UI      config.UIConfig
}

func loadRuntimeConfig(cliConfigPath string) (runtimeConfig, configLoadResult, error) {
	candidate, candidates, ok := pickExistingConfigCandidate(cliConfigPath, os.Getenv("GATEWAY_CONFIG"), os.Executable, os.Getwd, fileExists)
	if !ok {
		generatedPath, generatedMode, err := handleMissingConfigFile(cliConfigPath, os.Getenv("GATEWAY_CONFIG"), os.Getwd)
		if err != nil {
			return runtimeConfig{}, configLoadResult{}, err
		}
		data, err := os.ReadFile(generatedPath)
		if err != nil {
			return runtimeConfig{}, configLoadResult{}, fmt.Errorf("read generated config path=%q: %w", generatedPath, err)
		}
		cfg, err := parseRuntimeConfigFromTopLevelYAML(data)
		if err != nil {
			return runtimeConfig{}, configLoadResult{}, fmt.Errorf("parse generated config path=%q: %w", generatedPath, err)
		}
		if err := cfg.Network.Validate(); err != nil {
			return runtimeConfig{}, configLoadResult{}, fmt.Errorf("validate generated network config path=%q: %w", generatedPath, err)
		}
		if err := cfg.UI.Validate(); err != nil {
			return runtimeConfig{}, configLoadResult{}, fmt.Errorf("validate generated ui config path=%q: %w", generatedPath, err)
		}
		return cfg, configLoadResult{Path: generatedPath, Source: configSourceDefaultGenerated, AutoGenerated: true, GeneratedAsMode: generatedMode, Candidates: candidates}, nil
	}

	data, err := os.ReadFile(candidate.path)
	if err != nil {
		return runtimeConfig{}, configLoadResult{}, fmt.Errorf("load network config path=%q source=%s: %w", candidate.path, candidate.source, err)
	}
	runtimeCfg, err := parseRuntimeConfigFromTopLevelYAML(data)
	if err != nil {
		return runtimeConfig{}, configLoadResult{}, fmt.Errorf("parse network config path=%q source=%s: %w", candidate.path, candidate.source, err)
	}
	if err := runtimeCfg.Network.Validate(); err != nil {
		return runtimeConfig{}, configLoadResult{}, fmt.Errorf("validate network config path=%q source=%s: %w", candidate.path, candidate.source, err)
	}
	if err := runtimeCfg.UI.Validate(); err != nil {
		return runtimeConfig{}, configLoadResult{}, fmt.Errorf("validate ui config path=%q source=%s: %w", candidate.path, candidate.source, err)
	}
	return runtimeCfg, configLoadResult{Path: candidate.path, Source: candidate.source, Candidates: candidates}, nil
}

type fullConfigFile struct {
	SIP             config.SIPConfig             `yaml:"sip,omitempty"`
	RTP             config.RTPConfig             `yaml:"rtp,omitempty"`
	TransportTuning config.TransportTuningConfig `yaml:"transport_tuning,omitempty"`
	Storage         map[string]any               `yaml:"storage,omitempty"`
	Observability   map[string]any               `yaml:"observability,omitempty"`
	UI              config.UIConfig              `yaml:"ui,omitempty"`
	Ops             map[string]any               `yaml:"ops,omitempty"`
	Network         config.NetworkConfig         `yaml:"network,omitempty"`
}

func parseRuntimeConfigFromTopLevelYAML(data []byte) (runtimeConfig, error) {
	var fileCfg fullConfigFile
	if err := yaml.Unmarshal(data, &fileCfg); err != nil {
		return runtimeConfig{}, err
	}
	networkCfg := config.DefaultNetworkConfig()
	uiCfg := config.DefaultUIConfig()
	if fileCfg.Network != (config.NetworkConfig{}) {
		networkCfg = fileCfg.Network
	}
	if fileCfg.SIP != (config.SIPConfig{}) {
		networkCfg.SIP = fileCfg.SIP
	}
	if fileCfg.RTP != (config.RTPConfig{}) {
		networkCfg.RTP = fileCfg.RTP
	}
	if fileCfg.TransportTuning != (config.TransportTuningConfig{}) {
		networkCfg.TransportTuning = fileCfg.TransportTuning
	}
	networkCfg.ApplyDefaults()
	if fileCfg.UI != (config.UIConfig{}) {
		uiCfg = fileCfg.UI
	}
	uiCfg.ApplyDefaults(networkCfg.SIP.ListenPort)
	return runtimeConfig{Network: networkCfg, UI: uiCfg}, nil
}

func defaultConfigYAML(osName string) ([]byte, error) {
	networkCfg := config.DefaultNetworkConfig()
	if osName == "windows" {
		networkCfg.SIP.ListenPort = pickFriendlySIPPort()
	}
	uiCfg := config.DefaultUIConfig()
	rtpPoolSize := config.RTPPortPoolSize(networkCfg.RTP.PortStart, networkCfg.RTP.PortEnd)
	recommendedRTPTransfers := config.RecommendedStableRTPTransfers(networkCfg.RTP.PortStart, networkCfg.RTP.PortEnd)
	inlineBodyBudget := config.RecommendedInlineBodyBudgetBytes(networkCfg.TransportTuning)
	rtpReorderBudget := config.RecommendedRTPReorderBufferBytes(networkCfg.TransportTuning)
	playbackRTPReorderBudget := config.RecommendedPlaybackRTPReorderBufferBytes(networkCfg.TransportTuning)
	var b strings.Builder
	b.WriteString("# generated by gateway init-config\n")
	fmt.Fprintf(&b, "# 专网/安全边界推荐端口规划：SIP=%d，RTP=%d-%d，映射=%d-%d（节点工作区），UI=%d\n", networkCfg.SIP.ListenPort, networkCfg.RTP.PortStart, networkCfg.RTP.PortEnd, config.DefaultMappingPortStart, config.DefaultMappingPortEnd, uiCfg.ListenPort)
	fmt.Fprintf(&b, "# 当前 RTP 端口池共 %d 个端口；按预留 %d%% 余量计算，建议稳定并发不超过 %d 路。\n", rtpPoolSize, config.RecommendedPortHeadroomPC, recommendedRTPTransfers)
	fmt.Fprintf(&b, "# 当前 INLINE 预算按 UDP 总预算 - 安全预留 - 封装开销 - headroom 计算，推荐正文不超过 %d 字节。\n", inlineBodyBudget)
	fmt.Fprintf(&b, "# RTP 乱序/轻微丢包等待预算≈(reorder_window + loss_tolerance) * payload = %d 字节；只用于等待迟到包和触发恢复，不代表允许静默丢字节。\n", rtpReorderBudget)
	fmt.Fprintf(&b, "# 浏览器 Range 播放专用预算≈(playback_reorder_window + playback_loss_tolerance) * payload = %d 字节；默认更偏向 Web 播放 HTTP MP4。\n\n", playbackRTPReorderBudget)
	b.WriteString("sip:\n")
	b.WriteString("  # SIP 建议固定使用 5060；如 Windows 首启已被占用，可保留工具自动生成的友好端口。\n")
	fmt.Fprintf(&b, "  enabled: true\n  listen_ip: 0.0.0.0\n  listen_port: %d\n  transport: %s\n\n", networkCfg.SIP.ListenPort, networkCfg.SIP.Transport)
	b.WriteString("rtp:\n")
	fmt.Fprintf(&b, "  # RTP 端口段建议固定为 %d-%d，避免与 SIP/UI/映射端口重叠。\n", networkCfg.RTP.PortStart, networkCfg.RTP.PortEnd)
	fmt.Fprintf(&b, "  # 本实现按 1 个 RTP 传输占用 1 个端口估算；%d 个端口≈%d 路理论上限，建议现场按 %d 路以内做稳定值。\n", rtpPoolSize, rtpPoolSize, recommendedRTPTransfers)
	fmt.Fprintf(&b, "  enabled: true\n  listen_ip: 0.0.0.0\n  port_start: %d\n  port_end: %d\n  transport: %s\n\n", networkCfg.RTP.PortStart, networkCfg.RTP.PortEnd, networkCfg.RTP.Transport)
	b.WriteString("storage:\n  temp_dir: ./data/temp\n  final_dir: ./data/final\n  audit_dir: ./data/audit\n  log_dir: ./data/logs\n\n")
	b.WriteString("observability:\n  log_level: info\n  pprof_enabled: false\n  metrics_enabled: true\n\n")
	b.WriteString("ui:\n")
	fmt.Fprintf(&b, "  # 管理面默认只绑定本机 127.0.0.1:%d；不要放到 RTP/映射端口段内。\n", uiCfg.ListenPort)
	fmt.Fprintf(&b, "  enabled: true\n  mode: embedded\n  listen_ip: 127.0.0.1\n  listen_port: %d\n  base_path: /\n\n", uiCfg.ListenPort)
	b.WriteString("ops:\n  run_mode: dev\n  allow_auto_init_config: true\n\n")
	b.WriteString("transport_tuning:\n")
	b.WriteString("  # secure_boundary 是安全边界专网默认档；现场优先只改注释中给出的少数项。\n")
	fmt.Fprintf(&b, "  mode: %s\n", networkCfg.TransportTuning.Mode)
	fmt.Fprintf(&b, "  # UDP 控制面预算建议 1300；可选/校验值 [1024,1400]。低于 1249 容易重现 request_control_oversize。\n  udp_control_max_bytes: %d\n  udp_catalog_max_bytes: %d\n", networkCfg.TransportTuning.UDPControlMaxBytes, networkCfg.TransportTuning.UDPCatalogMaxBytes)
	fmt.Fprintf(&b, "  # INLINE 预算推荐正文≈%d 字节；现场尽量不要单独放大 budget，而是优先减小响应。\n", inlineBodyBudget)
	fmt.Fprintf(&b, "  inline_response_udp_budget_bytes: %d\n  inline_response_safety_reserve_bytes: %d\n  inline_response_envelope_overhead_bytes: %d\n  inline_response_headroom_ratio: %.2f\n  inline_response_headroom_percent: %d\n", networkCfg.TransportTuning.InlineResponseUDPBudgetBytes, networkCfg.TransportTuning.InlineResponseSafetyReserveBytes, networkCfg.TransportTuning.InlineResponseEnvelopeOverheadBytes, networkCfg.TransportTuning.InlineResponseHeadroomRatio, networkCfg.TransportTuning.InlineResponseHeadroomPercent)
	fmt.Fprintf(&b, "  # 并发调度：request/callback 推荐 6；bulk_open 推荐 4；segment_child 推荐 8；small wait 推荐 1500ms。\n  udp_request_parallelism_per_device: %d\n  udp_callback_parallelism_per_peer: %d\n  udp_bulk_parallelism_per_device: %d\n  udp_segment_parallelism_per_device: %d\n  udp_small_request_max_wait_ms: %d\n", networkCfg.TransportTuning.UDPRequestParallelismPerDevice, networkCfg.TransportTuning.UDPCallbackParallelismPerPeer, networkCfg.TransportTuning.UDPBulkParallelismPerDevice, networkCfg.TransportTuning.UDPSegmentParallelismPerDevice, networkCfg.TransportTuning.UDPSmallRequestMaxWaitMS)
	fmt.Fprintf(&b, "  # RTP 主通道：payload 推荐 1200；bitrate 推荐 16777216；min_spacing 推荐 500us。\n")
	fmt.Fprintf(&b, "  # 当前 RTP 缓冲预算≈(%d+%d)*%d=%d 字节；播放专用预算≈(%d+%d)*%d=%d 字节。\n", networkCfg.TransportTuning.BoundaryRTPReorderWindowPackets, networkCfg.TransportTuning.BoundaryRTPLossTolerancePackets, networkCfg.TransportTuning.BoundaryRTPPayloadBytes, rtpReorderBudget, networkCfg.TransportTuning.BoundaryPlaybackRTPReorderWindowPackets, networkCfg.TransportTuning.BoundaryPlaybackRTPLossTolerancePackets, networkCfg.TransportTuning.BoundaryRTPPayloadBytes, playbackRTPReorderBudget)
	fmt.Fprintf(&b, "  boundary_rtp_payload_bytes: %d\n  boundary_rtp_bitrate_bps: %d\n  boundary_rtp_min_spacing_us: %d\n  boundary_rtp_reorder_window_packets: %d\n  boundary_rtp_loss_tolerance_packets: %d\n  boundary_rtp_gap_timeout_ms: %d\n", networkCfg.TransportTuning.BoundaryRTPPayloadBytes, networkCfg.TransportTuning.BoundaryRTPBitrateBps, networkCfg.TransportTuning.BoundaryRTPMinSpacingUS, networkCfg.TransportTuning.BoundaryRTPReorderWindowPackets, networkCfg.TransportTuning.BoundaryRTPLossTolerancePackets, networkCfg.TransportTuning.BoundaryRTPGapTimeoutMS)
	fmt.Fprintf(&b, "  # 浏览器 Range 播放专用覆盖：只在 video/audio/mp4 等播放型 Range 请求命中时生效，不影响普通下载。\n")
	fmt.Fprintf(&b, "  boundary_playback_rtp_reorder_window_packets: %d\n  boundary_playback_rtp_loss_tolerance_packets: %d\n  boundary_playback_rtp_gap_timeout_ms: %d\n", networkCfg.TransportTuning.BoundaryPlaybackRTPReorderWindowPackets, networkCfg.TransportTuning.BoundaryPlaybackRTPLossTolerancePackets, networkCfg.TransportTuning.BoundaryPlaybackRTPGapTimeoutMS)
	fmt.Fprintf(&b, "  boundary_fixed_window_bytes: %d\n  boundary_fixed_window_threshold_bytes: %d\n  boundary_segment_concurrency: %d\n  boundary_segment_retries: %d\n  boundary_resume_max_attempts: %d\n  boundary_resume_per_range_retries: %d\n", networkCfg.TransportTuning.BoundaryFixedWindowBytes, networkCfg.TransportTuning.BoundaryFixedWindowThreshold, networkCfg.TransportTuning.BoundarySegmentConcurrency, networkCfg.TransportTuning.BoundarySegmentRetries, networkCfg.TransportTuning.BoundaryResumeMaxAttempts, networkCfg.TransportTuning.BoundaryResumePerRangeRetries)
	fmt.Fprintf(&b, "  boundary_response_start_wait_ms: %d\n  boundary_range_response_start_wait_ms: %d\n", networkCfg.TransportTuning.BoundaryResponseStartWaitMS, networkCfg.TransportTuning.BoundaryRangeResponseWaitMS)
	fmt.Fprintf(&b, "  boundary_http_window_bytes: %d\n  boundary_http_window_threshold_bytes: %d\n  boundary_http_segment_concurrency: %d\n  boundary_http_segment_retries: %d\n", networkCfg.TransportTuning.BoundaryHTTPWindowBytes, networkCfg.TransportTuning.BoundaryHTTPWindowThreshold, networkCfg.TransportTuning.BoundaryHTTPSegmentConcurrency, networkCfg.TransportTuning.BoundaryHTTPSegmentRetries)
	fmt.Fprintf(&b, "  # 热点播放：默认只开缓存，不盲目预取。prefetch 建议 [0,2]；recent probe abort 会触发 open-ended range 直走 range_primary。\n  adaptive_playback_hot_window_bytes: %d\n  adaptive_playback_segment_cache_bytes: %d\n  adaptive_playback_segment_cache_ttl_ms: %d\n  adaptive_playback_prefetch_segments: %d\n  adaptive_primary_segment_after_failures: %d\n", networkCfg.TransportTuning.AdaptivePlaybackHotWindowBytes, networkCfg.TransportTuning.AdaptivePlaybackSegmentCacheBytes, networkCfg.TransportTuning.AdaptivePlaybackSegmentCacheTTLMS, networkCfg.TransportTuning.AdaptivePlaybackPrefetchSegments, networkCfg.TransportTuning.AdaptivePrimarySegmentAfterFailures)
	fmt.Fprintf(&b, "  standard_window_bytes: %d\n  standard_window_threshold_bytes: %d\n  standard_segment_concurrency: %d\n  standard_segment_retries: %d\n", networkCfg.TransportTuning.StandardWindowBytes, networkCfg.TransportTuning.StandardWindowThreshold, networkCfg.TransportTuning.StandardSegmentConcurrency, networkCfg.TransportTuning.StandardSegmentRetries)
	return []byte(b.String()), nil
}

func resolveConfigOutputPath(cliConfigPath string, envConfigPath string, getwd func() (string, error), executablePath func() (string, error), osName string) string {
	if p := strings.TrimSpace(cliConfigPath); p != "" {
		return p
	}
	if p := strings.TrimSpace(envConfigPath); p != "" {
		return p
	}
	if osName == "windows" {
		exeDir := executableDir(getExecutablePathOrEmpty(executablePath))
		if exeDir != "" {
			return filepath.Join(exeDir, "configs", "config.yaml")
		}
	}
	cwd, err := getwd()
	if err != nil {
		cwd = "."
	}
	return filepath.Join(cwd, "configs", "config.yaml")
}

func writeConfigIfNotExists(path string, template bool) (bool, error) {
	if fileExists(path) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	b, err := defaultConfigYAML(runtime.GOOS)
	if err != nil {
		return false, err
	}
	if template {
		b = append([]byte("# PRODUCTION TEMPLATE: 请先修改参数后再启动网关\n"), b...)
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func handleMissingConfigFile(cliConfigPath string, envConfigPath string, getwd func() (string, error)) (string, string, error) {
	mode := resolveRunMode()
	path := resolveConfigOutputPath(cliConfigPath, envConfigPath, getwd, os.Executable, runtime.GOOS)
	created, err := writeConfigIfNotExists(path, mode == "prod")
	if err != nil {
		return "", mode, err
	}
	if created {
		log.Printf("config file auto generated path=%q mode=%s", path, mode)
	} else {
		log.Printf("config file already exists, skip generation path=%q", path)
	}
	if mode == "prod" {
		return path, mode, errors.New("production mode detected, template generated. please edit config and restart")
	}
	return path, mode, nil
}

func pickExistingConfigCandidate(cliConfigPath string, envConfigPath string, executablePath func() (string, error), getwd func() (string, error), exists func(string) bool) (configCandidate, []string, bool) {
	exePath := getExecutablePathOrEmpty(executablePath)
	cwd, err := getwd()
	if err != nil {
		cwd = "."
	}
	allCandidates := configCandidates(cliConfigPath, envConfigPath, executableDir(exePath), cwd, runtime.GOOS)
	candidatePaths := make([]string, 0, len(allCandidates))
	for _, item := range allCandidates {
		candidatePaths = append(candidatePaths, fmt.Sprintf("%s (%s)", item.path, item.source))
	}
	for _, candidate := range allCandidates {
		if exists(candidate.path) {
			return candidate, candidatePaths, true
		}
	}
	return configCandidate{}, candidatePaths, false
}

func configCandidates(cliConfigPath string, envConfigPath string, exeDir string, cwd string, osName string) []configCandidate {
	candidates := make([]configCandidate, 0, 6)
	if p := strings.TrimSpace(cliConfigPath); p != "" {
		if osName == "windows" && filepath.IsAbs(p) == false && exeDir != "" {
			candidates = append(candidates, configCandidate{path: filepath.Join(exeDir, p), source: configSourceCLI})
		}
		candidates = append(candidates, configCandidate{path: p, source: configSourceCLI})
	}
	if p := strings.TrimSpace(envConfigPath); p != "" {
		if osName == "windows" && filepath.IsAbs(p) == false && exeDir != "" {
			candidates = append(candidates, configCandidate{path: filepath.Join(exeDir, p), source: configSourceEnv})
		}
		candidates = append(candidates, configCandidate{path: p, source: configSourceEnv})
	}
	if exeDir != "" {
		candidates = append(candidates,
			configCandidate{path: filepath.Join(exeDir, "configs", "config.yaml"), source: configSourceExeDir},
			configCandidate{path: filepath.Join(exeDir, "config.yaml"), source: configSourceExeDir},
		)
	}
	candidates = append(candidates,
		configCandidate{path: filepath.Join(cwd, "configs", "config.yaml"), source: configSourceCWD},
		configCandidate{path: filepath.Join(cwd, "config.yaml"), source: configSourceCWD},
	)
	return candidates
}

func getExecutablePathOrEmpty(executablePath func() (string, error)) string {
	if executablePath == nil {
		return ""
	}
	path, err := executablePath()
	if err != nil {
		return ""
	}
	return path
}

func executableDir(executablePath string) string {
	if executablePath == "" {
		return ""
	}
	if strings.Contains(executablePath, "\\") {
		normalized := strings.ReplaceAll(executablePath, "\\", "/")
		return strings.ReplaceAll(path.Dir(normalized), "/", "\\")
	}
	return filepath.Dir(executablePath)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func parseBoolEnv(name string) bool {
	raw := strings.TrimSpace(os.Getenv(name))
	if raw == "" {
		return false
	}
	v, err := strconv.ParseBool(raw)
	if err != nil {
		return false
	}
	return v
}

func extractToolCommand(args []string) (string, []string, bool) {
	if len(args) == 0 {
		return "", nil, false
	}
	toolCommands := map[string]struct{}{"init-config": {}, "print-default-config": {}, "validate-config": {}}
	for idx, arg := range args {
		for _, token := range strings.Fields(strings.ToLower(strings.TrimSpace(strings.ReplaceAll(arg, `\\n`, "\n")))) {
			token = strings.Trim(token, `"'`)
			if _, ok := toolCommands[token]; ok {
				return token, args[idx+1:], true
			}
		}
	}
	return "", nil, false
}

type packetConnCloser struct{ net.PacketConn }
