package configdoc

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Outputs struct {
	MarkdownPath string
	ExamplePath  string
	DevPath      string
	TestPath     string
	ProdPath     string
}

func GenerateAll(repoRoot string) (Outputs, error) {
	outputs := Outputs{
		MarkdownPath: filepath.Join(repoRoot, "docs", "generated", "config-params.md"),
		ExamplePath:  filepath.Join(repoRoot, "configs", "generated", "config.example.generated.yaml"),
		DevPath:      filepath.Join(repoRoot, "configs", "generated", "config.dev.template.yaml"),
		TestPath:     filepath.Join(repoRoot, "configs", "generated", "config.test.template.yaml"),
		ProdPath:     filepath.Join(repoRoot, "configs", "generated", "config.prod.template.yaml"),
	}
	if err := write(outputs.MarkdownPath, RenderMarkdown()); err != nil {
		return Outputs{}, err
	}
	if err := write(outputs.ExamplePath, RenderYAML(ProfileExample)); err != nil {
		return Outputs{}, err
	}
	if err := write(outputs.DevPath, RenderYAML(ProfileDev)); err != nil {
		return Outputs{}, err
	}
	if err := write(outputs.TestPath, RenderYAML(ProfileTest)); err != nil {
		return Outputs{}, err
	}
	if err := write(outputs.ProdPath, RenderYAML(ProfileProd)); err != nil {
		return Outputs{}, err
	}
	return outputs, nil
}

func RenderMarkdown() string {
	var b strings.Builder
	b.WriteString("# 配置参数手册（自动生成）\n\n")
	b.WriteString("> 由 `go run ./cmd/configdocgen` 生成，请勿手动编辑。\n\n")
	b.WriteString("高风险网络参数会标记为 `⚠️ HIGH-NET`，变更前请执行联调与端口占用检查。\n\n")
	b.WriteString("| 参数名 | 类型 | 默认值 | 热更新 | 风险等级 | 说明 |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, item := range Catalog() {
		hotReload := "否"
		if item.HotReload {
			hotReload = "是"
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | %s | %s | %s |\n", item.Name, item.Type, formatDefault(item.Default), hotReload, markRisk(item), item.Description))
	}
	return b.String()
}

func RenderYAML(profile Profile) string {
	values := profileValues(profile)
	var b strings.Builder
	b.WriteString("# Code generated by cmd/configdocgen; DO NOT EDIT.\n")
	b.WriteString("server:\n")
	b.WriteString(fmt.Sprintf("  port: %v\n\n", values["server.port"]))
	b.WriteString("storage:\n")
	b.WriteString(fmt.Sprintf("  temp_dir: %s\n", toYAMLValue(values["storage.temp_dir"])))
	b.WriteString(fmt.Sprintf("  final_dir: %s\n", toYAMLValue(values["storage.final_dir"])))
	b.WriteString(fmt.Sprintf("  audit_dir: %s\n", toYAMLValue(values["storage.audit_dir"])))
	b.WriteString(fmt.Sprintf("  log_dir: %s\n\n", toYAMLValue(values["storage.log_dir"])))
	b.WriteString("network:\n")
	b.WriteString("  sip:\n")
	b.WriteString(fmt.Sprintf("    enabled: %v\n", values["network.sip.enabled"]))
	b.WriteString(fmt.Sprintf("    listen_ip: %s\n", toYAMLValue(values["network.sip.listen_ip"])))
	b.WriteString(fmt.Sprintf("    listen_port: %v\n", values["network.sip.listen_port"]))
	b.WriteString(fmt.Sprintf("    transport: %s\n", toYAMLValue(values["network.sip.transport"])))
	b.WriteString(fmt.Sprintf("    advertise_ip: %s\n", toYAMLValue(values["network.sip.advertise_ip"])))
	b.WriteString(fmt.Sprintf("    domain: %s\n", toYAMLValue(values["network.sip.domain"])))
	b.WriteString(fmt.Sprintf("    max_message_bytes: %v\n", values["network.sip.max_message_bytes"]))
	b.WriteString(fmt.Sprintf("    read_timeout_ms: %v\n", values["network.sip.read_timeout_ms"]))
	b.WriteString(fmt.Sprintf("    write_timeout_ms: %v\n", values["network.sip.write_timeout_ms"]))
	b.WriteString(fmt.Sprintf("    idle_timeout_ms: %v\n\n", values["network.sip.idle_timeout_ms"]))
	b.WriteString("  rtp:\n")
	b.WriteString(fmt.Sprintf("    enabled: %v\n", values["network.rtp.enabled"]))
	b.WriteString(fmt.Sprintf("    listen_ip: %s\n", toYAMLValue(values["network.rtp.listen_ip"])))
	b.WriteString(fmt.Sprintf("    advertise_ip: %s\n", toYAMLValue(values["network.rtp.advertise_ip"])))
	b.WriteString(fmt.Sprintf("    port_start: %v\n", values["network.rtp.port_start"]))
	b.WriteString(fmt.Sprintf("    port_end: %v\n", values["network.rtp.port_end"]))
	b.WriteString(fmt.Sprintf("    transport: %s\n", toYAMLValue(values["network.rtp.transport"])))
	b.WriteString(fmt.Sprintf("    max_packet_bytes: %v\n", values["network.rtp.max_packet_bytes"]))
	b.WriteString(fmt.Sprintf("    tcp_read_timeout_ms: %v\n", values["network.rtp.tcp_read_timeout_ms"]))
	b.WriteString(fmt.Sprintf("    tcp_write_timeout_ms: %v\n", values["network.rtp.tcp_write_timeout_ms"]))
	b.WriteString(fmt.Sprintf("    tcp_keepalive_enabled: %v\n", values["network.rtp.tcp_keepalive_enabled"]))
	b.WriteString(fmt.Sprintf("    max_tcp_sessions: %v\n", values["network.rtp.max_tcp_sessions"]))
	b.WriteString(fmt.Sprintf("    max_inflight_transfers: %v\n", values["network.rtp.max_inflight_transfers"]))
	b.WriteString(fmt.Sprintf("    receive_buffer_bytes: %v\n", values["network.rtp.receive_buffer_bytes"]))
	b.WriteString(fmt.Sprintf("    transfer_timeout_ms: %v\n", values["network.rtp.transfer_timeout_ms"]))
	b.WriteString(fmt.Sprintf("    retransmit_max_rounds: %v\n\n", values["network.rtp.retransmit_max_rounds"]))
	b.WriteString("media:\n")
	b.WriteString("  port_range:\n")
	b.WriteString(fmt.Sprintf("    start: %v\n", values["media.port_range.start"]))
	b.WriteString(fmt.Sprintf("    end: %v\n\n", values["media.port_range.end"]))
	b.WriteString("node:\n")
	b.WriteString(fmt.Sprintf("  role: %s\n", toYAMLValue(values["node.role"])))
	return b.String()
}

func write(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func toYAMLValue(v any) string {
	s, ok := v.(string)
	if !ok {
		return fmt.Sprintf("%v", v)
	}
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#{}[]") || strings.Contains(s, " ") {
		return fmt.Sprintf("%q", s)
	}
	return s
}
