package startupsummary

import (
	"fmt"
	"strings"
	"time"

	"siptunnel/internal/config"
	"siptunnel/internal/nodeconfig"
)

type Summary struct {
	NodeID                 string                     `json:"node_id"`
	RegistrationStatus     string                     `json:"registration_status,omitempty"`
	HeartbeatStatus        string                     `json:"heartbeat_status,omitempty"`
	LastRegisterTime       string                     `json:"last_register_time,omitempty"`
	LastHeartbeatTime      string                     `json:"last_heartbeat_time,omitempty"`
	LastFailureReason      string                     `json:"last_failure_reason,omitempty"`
	NextRetryTime          string                     `json:"next_retry_time,omitempty"`
	NetworkMode            config.NetworkMode         `json:"network_mode"`
	Capability             config.Capability          `json:"capability"`
	CapabilitySummary      CapabilitySummary          `json:"capability_summary"`
	TransportPlan          config.TunnelTransportPlan `json:"transport_plan"`
	TransportTuningSummary TransportTuningSummary     `json:"transport_tuning_summary"`
	ActiveStrategySummary  ActiveStrategySummary      `json:"active_strategy_summary"`
	UIDeliverySummary      UIDeliverySummary          `json:"ui_delivery_summary"`
	BoundPeer              *PeerBinding               `json:"bound_peer,omitempty"`
	PeerBindingError       string                     `json:"peer_binding_error,omitempty"`
	CurrentNetworkMode     config.NetworkMode         `json:"current_network_mode,omitempty"`
	CurrentCapability      config.Capability          `json:"current_capability,omitempty"`
	CompatibilityStatus    nodeconfig.CheckResult     `json:"compatibility_status,omitempty"`
	ConfigPath             string                     `json:"config_path"`
	ConfigSource           string                     `json:"config_source"`
	RunMode                string                     `json:"run_mode,omitempty"`
	AutoGeneratedConfig    bool                       `json:"auto_generated_config,omitempty"`
	ConfigCandidates       []string                   `json:"config_candidates,omitempty"`
	UIMode                 string                     `json:"ui_mode"`
	UIURL                  string                     `json:"ui_url"`
	APIURL                 string                     `json:"api_url"`
	SIPListen              ListenEndpoint             `json:"sip_listen"`
	RTPListen              RTPListen                  `json:"rtp_listen"`
	StorageDirs            StorageDirs                `json:"storage_dirs"`
	BusinessExecution      BusinessExecutionStatus    `json:"business_execution"`
	SelfCheckSummary       SelfCheckSummary           `json:"self_check_summary"`
	DataSources            DataSources                `json:"data_sources"`
}

type PeerBinding struct {
	PeerNodeID        string `json:"peer_node_id"`
	PeerName          string `json:"peer_name"`
	PeerSignalingIP   string `json:"peer_signaling_ip"`
	PeerSignalingPort int    `json:"peer_signaling_port"`
}

type DataSources struct {
	NodeConfig string `json:"node_config"`
	Peers      string `json:"peers"`
	Mappings   string `json:"mappings"`
	Mode       string `json:"mode"`
	Capability string `json:"capability"`
}

type BusinessExecutionStatus struct {
	State      string `json:"state"`
	RouteCount int    `json:"route_count"`
	Message    string `json:"message"`
	Impact     string `json:"impact"`
}

type ListenEndpoint struct {
	IP        string `json:"ip"`
	Port      int    `json:"port"`
	Transport string `json:"transport"`
}

type RTPListen struct {
	IP        string `json:"ip"`
	PortRange string `json:"port_range"`
	Transport string `json:"transport"`
}

type StorageDirs struct {
	TempDir  string `json:"temp_dir"`
	FinalDir string `json:"final_dir"`
	AuditDir string `json:"audit_dir"`
	LogDir   string `json:"log_dir"`
}

type CapabilitySummary struct {
	Supported   []string                `json:"supported"`
	Unsupported []string                `json:"unsupported"`
	Items       []config.CapabilityItem `json:"items"`
}

type SelfCheckSummary struct {
	GeneratedAt string `json:"generated_at"`
	Overall     string `json:"overall"`
	Info        int    `json:"info"`
	Warn        int    `json:"warn"`
	Error       int    `json:"error"`
}

type UIDeliverySummary struct {
	MetadataPresent         bool   `json:"metadata_present"`
	ConsistencyStatus       string `json:"consistency_status"`
	ConsistencyDetail       string `json:"consistency_detail"`
	BuildNonce              string `json:"build_nonce"`
	EmbeddedAt              string `json:"embedded_at"`
	UISourceLatestWrite     string `json:"ui_source_latest_write"`
	EmbeddedHashSHA256      string `json:"embedded_hash_sha256"`
	AssetBaseMode           string `json:"asset_base_mode"`
	RouterBasePathPolicy    string `json:"router_base_path_policy"`
	DeliveryGuardStatus     string `json:"delivery_guard_status"`
	DeliveryGuardDetail     string `json:"delivery_guard_detail"`
	DeliveryGuardRemoved    int    `json:"delivery_guard_removed_count"`
	DeliveryGuardRemaining  int    `json:"delivery_guard_remaining_count"`
	DeliveryGuardActiveHits int    `json:"delivery_guard_hit_count"`
}

type ActiveStrategySummary struct {
	ResponseModePolicy            string `json:"response_mode_policy"`
	LargeResponseDeliveryFamily   string `json:"large_response_delivery_family"`
	SegmentedProfileSelector      string `json:"segmented_profile_selector"`
	EntrySelectionPolicy          string `json:"entry_selection_policy"`
	UDPControlHeaderPolicy        string `json:"udp_control_header_policy"`
	BoundaryRTPSendProfile        string `json:"boundary_rtp_send_profile"`
	BoundaryRTPToleranceProfile   string `json:"boundary_rtp_tolerance_profile"`
	PlaybackRTPToleranceProfile   string `json:"playback_rtp_tolerance_profile"`
	GenericDownloadRTPSendProfile string `json:"generic_download_rtp_send_profile"`
	GenericDownloadRTPTolerance   string `json:"generic_download_rtp_tolerance_profile"`
	GenericDownloadCircuitPolicy  string `json:"generic_download_circuit_policy"`
	GenericDownloadGuardPolicy    string `json:"generic_download_guard_policy"`
}

type TransportTuningSummary struct {
	UDPControlMaxBytes                  int     `json:"udp_control_max_bytes"`
	UDPCatalogMaxBytes                  int     `json:"udp_catalog_max_bytes"`
	EffectiveInlineBudgetBytes          int     `json:"effective_inline_budget_bytes"`
	UDPRequestParallelismPerDevice      int     `json:"udp_request_parallelism_per_device"`
	UDPCallbackParallelismPerPeer       int     `json:"udp_callback_parallelism_per_peer"`
	UDPBulkParallelismPerDevice         int     `json:"udp_bulk_parallelism_per_device"`
	UDPSegmentParallelismPerDevice      int     `json:"udp_segment_parallelism_per_device"`
	UDPSmallRequestMaxWaitMS            int     `json:"udp_small_request_max_wait_ms"`
	AdaptivePlaybackHotWindowBytes      int64   `json:"adaptive_playback_hot_window_bytes"`
	AdaptivePlaybackSegmentCacheBytes   int64   `json:"adaptive_playback_segment_cache_bytes"`
	AdaptivePlaybackSegmentCacheTTLMS   int     `json:"adaptive_playback_segment_cache_ttl_ms"`
	AdaptivePlaybackPrefetchSegments    int     `json:"adaptive_playback_prefetch_segments"`
	AdaptivePrimarySegmentAfterFails    int     `json:"adaptive_primary_segment_after_failures"`
	GenericDownloadWindowBytes          int64   `json:"generic_download_window_bytes"`
	GenericDownloadOpenEndedWindowBytes int64   `json:"generic_download_open_ended_window_bytes"`
	GenericDownloadSegmentConcurrency   int     `json:"generic_download_segment_concurrency"`
	GenericDownloadTotalBitrateBps      int     `json:"generic_download_total_bitrate_bps"`
	GenericDownloadMinPerTransferBps    int     `json:"generic_download_min_per_transfer_bitrate_bps"`
	GenericDownloadCircuitThreshold     int     `json:"generic_download_circuit_failure_threshold"`
	GenericDownloadCircuitOpenMS        int     `json:"generic_download_circuit_open_ms"`
	GenericDownloadRTPBitrateBps        int     `json:"generic_download_rtp_bitrate_bps"`
	GenericDownloadRTPReorderWindow     int     `json:"generic_download_rtp_reorder_window_packets"`
	GenericDownloadRTPLossTolerance     int     `json:"generic_download_rtp_loss_tolerance_packets"`
	GenericDownloadRTPGapTimeoutMS      int     `json:"generic_download_rtp_gap_timeout_ms"`
	InlineResponseHeadroomRatio         float64 `json:"inline_response_headroom_ratio"`
	ResponseModePolicy                  string  `json:"response_mode_policy"`
}

func (s Summary) ToLogText() string {
	generatedAt := s.SelfCheckSummary.GeneratedAt
	if generatedAt == "" {
		generatedAt = time.Now().UTC().Format(time.RFC3339)
	}
	lines := []string{
		"startup summary:",
		fmt.Sprintf("- node_id: %s", safeValue(s.NodeID)),
		fmt.Sprintf("- config: path=%s source=%s", safeValue(s.ConfigPath), safeValue(s.ConfigSource)),
		fmt.Sprintf("- run_mode: %s", safeValue(s.RunMode)),
		fmt.Sprintf("- auto_generated_config: %t", s.AutoGeneratedConfig),
		fmt.Sprintf("- ui: mode=%s url=%s", safeValue(s.UIMode), safeValue(s.UIURL)),
		fmt.Sprintf("- api_url: %s", safeValue(s.APIURL)),
		fmt.Sprintf("- session: registration=%s heartbeat=%s last_register=%s last_heartbeat=%s next_retry=%s failure=%s", safeValue(s.RegistrationStatus), safeValue(s.HeartbeatStatus), safeValue(s.LastRegisterTime), safeValue(s.LastHeartbeatTime), safeValue(s.NextRetryTime), safeValue(s.LastFailureReason)),
		fmt.Sprintf("- network_mode: %s", safeValue(string(s.NetworkMode))),
		fmt.Sprintf("- capability_supported: %s", safeValue(strings.Join(s.CapabilitySummary.Supported, ","))),
		fmt.Sprintf("- capability_unsupported: %s", safeValue(strings.Join(s.CapabilitySummary.Unsupported, ","))),
		fmt.Sprintf("- transport_plan: req_meta=%s req_body=%s resp_meta=%s resp_body=%s req_limit=%d resp_limit=%d", safeValue(s.TransportPlan.RequestMetaTransport), safeValue(s.TransportPlan.RequestBodyTransport), safeValue(s.TransportPlan.ResponseMetaTransport), safeValue(s.TransportPlan.ResponseBodyTransport), s.TransportPlan.RequestBodySizeLimit, s.TransportPlan.ResponseBodySizeLimit),
		fmt.Sprintf("- effective_transport: udp_control_max_bytes=%d udp_catalog_max_bytes=%d effective_inline_budget_bytes=%d udp_request_parallelism_per_device=%d udp_callback_parallelism_per_peer=%d udp_bulk_parallelism_per_device=%d udp_segment_parallelism_per_device=%d udp_small_request_max_wait_ms=%d adaptive_playback_hot_window_bytes=%d adaptive_playback_segment_cache_bytes=%d adaptive_playback_segment_cache_ttl_ms=%d adaptive_playback_prefetch_segments=%d adaptive_primary_segment_after_failures=%d generic_download_window_bytes=%d generic_download_open_ended_window_bytes=%d generic_download_segment_concurrency=%d generic_download_total_bitrate_bps=%d generic_download_min_per_transfer_bitrate_bps=%d generic_download_circuit_failure_threshold=%d generic_download_circuit_open_ms=%d generic_download_rtp_bitrate_bps=%d generic_download_rtp_reorder_window_packets=%d generic_download_rtp_loss_tolerance_packets=%d generic_download_rtp_gap_timeout_ms=%d inline_response_headroom_ratio=%.2f response_mode_policy=%s", s.TransportTuningSummary.UDPControlMaxBytes, s.TransportTuningSummary.UDPCatalogMaxBytes, s.TransportTuningSummary.EffectiveInlineBudgetBytes, s.TransportTuningSummary.UDPRequestParallelismPerDevice, s.TransportTuningSummary.UDPCallbackParallelismPerPeer, s.TransportTuningSummary.UDPBulkParallelismPerDevice, s.TransportTuningSummary.UDPSegmentParallelismPerDevice, s.TransportTuningSummary.UDPSmallRequestMaxWaitMS, s.TransportTuningSummary.AdaptivePlaybackHotWindowBytes, s.TransportTuningSummary.AdaptivePlaybackSegmentCacheBytes, s.TransportTuningSummary.AdaptivePlaybackSegmentCacheTTLMS, s.TransportTuningSummary.AdaptivePlaybackPrefetchSegments, s.TransportTuningSummary.AdaptivePrimarySegmentAfterFails, s.TransportTuningSummary.GenericDownloadWindowBytes, s.TransportTuningSummary.GenericDownloadOpenEndedWindowBytes, s.TransportTuningSummary.GenericDownloadSegmentConcurrency, s.TransportTuningSummary.GenericDownloadTotalBitrateBps, s.TransportTuningSummary.GenericDownloadMinPerTransferBps, s.TransportTuningSummary.GenericDownloadCircuitThreshold, s.TransportTuningSummary.GenericDownloadCircuitOpenMS, s.TransportTuningSummary.GenericDownloadRTPBitrateBps, s.TransportTuningSummary.GenericDownloadRTPReorderWindow, s.TransportTuningSummary.GenericDownloadRTPLossTolerance, s.TransportTuningSummary.GenericDownloadRTPGapTimeoutMS, s.TransportTuningSummary.InlineResponseHeadroomRatio, safeValue(s.TransportTuningSummary.ResponseModePolicy)),
		fmt.Sprintf("- active_strategy_snapshot: response_mode_policy=%s large_response_delivery_family=%s segmented_profile_selector=%s entry_selection_policy=%s udp_control_header_policy=%s boundary_rtp_send=%s boundary_rtp_tolerance=%s playback_rtp_tolerance=%s generic_download_rtp_send=%s generic_download_rtp_tolerance=%s generic_download_circuit=%s generic_download_guard=%s", safeValue(s.ActiveStrategySummary.ResponseModePolicy), safeValue(s.ActiveStrategySummary.LargeResponseDeliveryFamily), safeValue(s.ActiveStrategySummary.SegmentedProfileSelector), safeValue(s.ActiveStrategySummary.EntrySelectionPolicy), safeValue(s.ActiveStrategySummary.UDPControlHeaderPolicy), safeValue(s.ActiveStrategySummary.BoundaryRTPSendProfile), safeValue(s.ActiveStrategySummary.BoundaryRTPToleranceProfile), safeValue(s.ActiveStrategySummary.PlaybackRTPToleranceProfile), safeValue(s.ActiveStrategySummary.GenericDownloadRTPSendProfile), safeValue(s.ActiveStrategySummary.GenericDownloadRTPTolerance), safeValue(s.ActiveStrategySummary.GenericDownloadCircuitPolicy), safeValue(s.ActiveStrategySummary.GenericDownloadGuardPolicy)),
		fmt.Sprintf("- ui_delivery_consistency: status=%s detail=%s build_nonce=%s embedded_at=%s ui_source_latest_write=%s embedded_hash=%s asset_base_mode=%s router_base_path_policy=%s delivery_guard_status=%s delivery_guard_detail=%s delivery_guard_removed=%d delivery_guard_remaining=%d delivery_guard_hits=%d metadata_present=%t", safeValue(s.UIDeliverySummary.ConsistencyStatus), safeValue(s.UIDeliverySummary.ConsistencyDetail), safeValue(s.UIDeliverySummary.BuildNonce), safeValue(s.UIDeliverySummary.EmbeddedAt), safeValue(s.UIDeliverySummary.UISourceLatestWrite), safeValue(s.UIDeliverySummary.EmbeddedHashSHA256), safeValue(s.UIDeliverySummary.AssetBaseMode), safeValue(s.UIDeliverySummary.RouterBasePathPolicy), safeValue(s.UIDeliverySummary.DeliveryGuardStatus), safeValue(s.UIDeliverySummary.DeliveryGuardDetail), s.UIDeliverySummary.DeliveryGuardRemoved, s.UIDeliverySummary.DeliveryGuardRemaining, s.UIDeliverySummary.DeliveryGuardActiveHits, s.UIDeliverySummary.MetadataPresent),
		fmt.Sprintf("- sip_listen: ip=%s port=%d transport=%s", safeValue(s.SIPListen.IP), s.SIPListen.Port, safeValue(s.SIPListen.Transport)),
		fmt.Sprintf("- rtp_listen: ip=%s port_range=%s transport=%s", safeValue(s.RTPListen.IP), safeValue(s.RTPListen.PortRange), safeValue(s.RTPListen.Transport)),
		fmt.Sprintf("- storage_dirs: temp=%s final=%s audit=%s log=%s", safeValue(s.StorageDirs.TempDir), safeValue(s.StorageDirs.FinalDir), safeValue(s.StorageDirs.AuditDir), safeValue(s.StorageDirs.LogDir)),
		fmt.Sprintf("- business_execution: state=%s route_count=%d message=%s impact=%s", safeValue(s.BusinessExecution.State), s.BusinessExecution.RouteCount, safeValue(s.BusinessExecution.Message), safeValue(s.BusinessExecution.Impact)),
		fmt.Sprintf("- self_check_summary: generated_at=%s overall=%s info=%d warn=%d error=%d", generatedAt, safeValue(s.SelfCheckSummary.Overall), s.SelfCheckSummary.Info, s.SelfCheckSummary.Warn, s.SelfCheckSummary.Error),
		fmt.Sprintf("- data_sources: node_config=%s peers=%s mappings=%s mode=%s capability=%s", safeValue(s.DataSources.NodeConfig), safeValue(s.DataSources.Peers), safeValue(s.DataSources.Mappings), safeValue(s.DataSources.Mode), safeValue(s.DataSources.Capability)),
	}
	if len(s.ConfigCandidates) > 0 {
		lines = append(lines, fmt.Sprintf("- config_candidates: %s", strings.Join(s.ConfigCandidates, " | ")))
	}
	return strings.Join(lines, "\n")
}

func safeValue(v string) string {
	v = strings.TrimSpace(v)
	if v == "" {
		return "-"
	}
	return v
}
