package startupsummary

import (
	"fmt"
	"strings"
	"testing"

	"siptunnel/internal/config"
)

func TestSummaryToLogText(t *testing.T) {
	cfg := config.DefaultNetworkConfig()
	cfg.Mode = config.NetworkModeSenderSIPReceiverRTP
	s := Summary{
		NodeID:            "gateway-a-01",
		NetworkMode:       config.NetworkModeSenderSIPReceiverRTP,
		Capability:        config.DeriveCapability(config.NetworkModeSenderSIPReceiverRTP),
		CapabilitySummary: CapabilitySummary{Supported: []string{"supports_small_request_body", "supports_large_response_body", "supports_streaming_response"}, Unsupported: []string{"supports_large_request_body", "supports_bidirectional_http_tunnel", "supports_transparent_http_proxy"}, Items: config.DeriveCapability(config.NetworkModeSenderSIPReceiverRTP).Matrix()},
		TransportPlan:     config.ResolveTransportPlanForConfig(cfg),
		TransportTuningSummary: TransportTuningSummary{
			UDPControlMaxBytes:                  1300,
			UDPCatalogMaxBytes:                  1300,
			EffectiveInlineBudgetBytes:          153,
			UDPRequestParallelismPerDevice:      4,
			UDPCallbackParallelismPerPeer:       4,
			UDPBulkParallelismPerDevice:         4,
			UDPSegmentParallelismPerDevice:      12,
			UDPSmallRequestMaxWaitMS:            1500,
			AdaptivePlaybackHotWindowBytes:      4194304,
			AdaptivePlaybackSegmentCacheBytes:   268435456,
			AdaptivePlaybackSegmentCacheTTLMS:   30000,
			AdaptivePlaybackPrefetchSegments:    2,
			AdaptivePrimarySegmentAfterFails:    2,
			GenericDownloadWindowBytes:          2097152,
			GenericDownloadOpenEndedWindowBytes: 8388608,
			GenericDownloadSegmentConcurrency:   1,
			GenericDownloadTotalBitrateBps:      33554432,
			GenericDownloadMinPerTransferBps:    2097152,
			GenericDownloadCircuitThreshold:     3,
			GenericDownloadCircuitOpenMS:        30000,
			GenericDownloadRTPBitrateBps:        8388608,
			GenericDownloadRTPReorderWindow:     512,
			GenericDownloadRTPLossTolerance:     192,
			GenericDownloadRTPGapTimeoutMS:      900,
			InlineResponseHeadroomRatio:         0.15,
			ResponseModePolicy:                  "AUTO(budget_driven_inline_or_rtp)",
		},
		ActiveStrategySummary: ActiveStrategySummary{
			ResponseModePolicy:            "AUTO(budget_driven_inline_or_rtp)",
			LargeResponseDeliveryFamily:   "stream_primary|range_primary|adaptive_segmented_primary|fallback_segmented",
			SegmentedProfileSelector:      "explicit_child>generic-rtp>boundary-rtp>boundary-http>standard-http",
			EntrySelectionPolicy:          "path_clean(dedupe_slash+dot_segment)=>normalized_path; root_or_default_document=>mapped_base; mapped_base/default_document=>mapped_base; mapped_base/*=>suffix_forward",
			UDPControlHeaderPolicy:        "selected_headers(content-type,auth,cookie,validators,range)>oversize_budget_rescue(cookie_trim+content_type_compact+login_validator_drop+bodyless_content_type_drop)>severe_budget_rescue(cookie64_or_auth_only)",
			BoundaryRTPSendProfile:        "boundary-rtp(payload=1200 bitrate_bps=16777216 spacing_us=250 socket_buffer_bytes=16777216 fec=true/8)",
			BoundaryRTPToleranceProfile:   "boundary(reorder=128 loss=48 gap_timeout_ms=300 fec=true/8)",
			PlaybackRTPToleranceProfile:   "range_playback(reorder=192 loss=64 gap_timeout_ms=450 fec=true/8)",
			GenericDownloadRTPSendProfile: "generic-rtp(payload=1200 bitrate_bps=8388608 socket_buffer_bytes=33554432 fec=true/8)",
			GenericDownloadRTPTolerance:   "generic_download(reorder=512 loss=192 gap_timeout_ms=900 fec=true/8)",
			GenericDownloadCircuitPolicy:  "threshold=3 open_ms=30000 severe_media_failure_threshold=1",
			GenericDownloadGuardPolicy:    "generic_download_profile_guard=aligned payload<=1200 bitrate<=8388608 socket_buffer<=33554432 reorder<=512 loss<=192 gap_timeout_ms<=900 fec=true/8",
		},
		UIDeliverySummary:   UIDeliverySummary{MetadataPresent: true, ConsistencyStatus: "aligned", ConsistencyDetail: "source, build bundle, embedded ui metadata, and delivery guard are aligned", BuildNonce: "20260322T010203-1234", EmbeddedAt: "2026-03-22 01:02:03", UISourceLatestWrite: "2026-03-22 00:59:59", EmbeddedHashSHA256: "deadbeef", AssetBaseMode: "relative_assets+basepath_meta", RouterBasePathPolicy: "meta_base_path_or_relative_history", DeliveryGuardStatus: "aligned", DeliveryGuardDetail: "no legacy drift detected", DeliveryGuardRemoved: 0, DeliveryGuardRemaining: 0, DeliveryGuardActiveHits: 0},
		ConfigPath:          "./configs/config.yaml",
		ConfigSource:        "cli",
		RunMode:             "dev",
		AutoGeneratedConfig: true,
		ConfigCandidates:    []string{"./configs/config.yaml (cwd)"},
		UIMode:              "embedded",
		UIURL:               "http://127.0.0.1:18080/",
		APIURL:              "http://127.0.0.1:18080/api",
		SIPListen:           ListenEndpoint{IP: "10.0.0.2", Port: 5060, Transport: "TCP"},
		RTPListen:           RTPListen{IP: "10.0.0.2", PortRange: "20000-20100", Transport: "UDP"},
		StorageDirs:         StorageDirs{TempDir: "./data/temp", FinalDir: "./data/final", AuditDir: "./data/audit", LogDir: "./data/logs"},
		BusinessExecution:   BusinessExecutionStatus{State: "protocol_only", RouteCount: 0, Message: "协议层可启动，业务执行层未激活（未加载下游 HTTP 隧道映射）", Impact: "仅完成 SIP/RTP 协议交互，不会执行 A 网 HTTP 落地"},
		SelfCheckSummary: SelfCheckSummary{
			GeneratedAt: "2026-01-02T03:04:05Z",
			Overall:     "warn",
			Info:        6,
			Warn:        1,
			Error:       0,
		},
	}
	text := s.ToLogText()
	for _, expected := range []string{
		"startup summary:",
		"node_id: gateway-a-01",
		"transport_plan: req_meta=sip_control req_body=sip_body_only resp_meta=sip_control resp_body=rtp_stream req_limit=65535 resp_limit=-1",
		"effective_transport: udp_control_max_bytes=1300 udp_catalog_max_bytes=1300 effective_inline_budget_bytes=153 udp_request_parallelism_per_device=4 udp_callback_parallelism_per_peer=4 udp_bulk_parallelism_per_device=4 udp_segment_parallelism_per_device=12 udp_small_request_max_wait_ms=1500 adaptive_playback_hot_window_bytes=4194304 adaptive_playback_segment_cache_bytes=268435456 adaptive_playback_segment_cache_ttl_ms=30000 adaptive_playback_prefetch_segments=2 adaptive_primary_segment_after_failures=2 generic_download_window_bytes=2097152 generic_download_open_ended_window_bytes=8388608 generic_download_segment_concurrency=1 generic_download_total_bitrate_bps=33554432 generic_download_min_per_transfer_bitrate_bps=2097152 generic_download_circuit_failure_threshold=3 generic_download_circuit_open_ms=30000 generic_download_rtp_bitrate_bps=8388608 generic_download_rtp_reorder_window_packets=512 generic_download_rtp_loss_tolerance_packets=192 generic_download_rtp_gap_timeout_ms=900 inline_response_headroom_ratio=0.15 response_mode_policy=AUTO(budget_driven_inline_or_rtp)",
		"active_strategy_snapshot: response_mode_policy=AUTO(budget_driven_inline_or_rtp) large_response_delivery_family=stream_primary|range_primary|adaptive_segmented_primary|fallback_segmented segmented_profile_selector=explicit_child>generic-rtp>boundary-rtp>boundary-http>standard-http entry_selection_policy=path_clean(dedupe_slash+dot_segment)=>normalized_path; root_or_default_document=>mapped_base; mapped_base/default_document=>mapped_base; mapped_base/*=>suffix_forward udp_control_header_policy=selected_headers(content-type,auth,cookie,validators,range)>oversize_budget_rescue(cookie_trim+content_type_compact+login_validator_drop+bodyless_content_type_drop)>severe_budget_rescue(cookie64_or_auth_only)",
		"ui_delivery_consistency: status=aligned detail=source, build bundle, embedded ui metadata, and delivery guard are aligned",
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("expected text contains %q\nfull:\n%s", expected, text)
		}
	}
}

func ExampleSummary_ToLogText() {
	cfg := config.DefaultNetworkConfig()
	cfg.Mode = config.NetworkModeSenderSIPRTPReceiverAll
	s := Summary{
		NodeID:            "gateway-a-01",
		NetworkMode:       config.NetworkModeSenderSIPRTPReceiverAll,
		Capability:        config.DeriveCapability(config.NetworkModeSenderSIPRTPReceiverAll),
		CapabilitySummary: CapabilitySummary{Supported: config.DeriveCapability(config.NetworkModeSenderSIPRTPReceiverAll).SupportedFeatures(), Unsupported: config.DeriveCapability(config.NetworkModeSenderSIPRTPReceiverAll).UnsupportedFeatures(), Items: config.DeriveCapability(config.NetworkModeSenderSIPRTPReceiverAll).Matrix()},
		TransportPlan:     config.ResolveTransportPlanForConfig(cfg),
		TransportTuningSummary: TransportTuningSummary{
			UDPControlMaxBytes:                  1300,
			UDPCatalogMaxBytes:                  1300,
			EffectiveInlineBudgetBytes:          153,
			UDPRequestParallelismPerDevice:      4,
			UDPCallbackParallelismPerPeer:       4,
			UDPBulkParallelismPerDevice:         4,
			UDPSegmentParallelismPerDevice:      12,
			UDPSmallRequestMaxWaitMS:            1500,
			AdaptivePlaybackHotWindowBytes:      4194304,
			AdaptivePlaybackSegmentCacheBytes:   268435456,
			AdaptivePlaybackSegmentCacheTTLMS:   30000,
			AdaptivePlaybackPrefetchSegments:    2,
			AdaptivePrimarySegmentAfterFails:    2,
			GenericDownloadWindowBytes:          2097152,
			GenericDownloadOpenEndedWindowBytes: 8388608,
			GenericDownloadSegmentConcurrency:   1,
			GenericDownloadTotalBitrateBps:      33554432,
			GenericDownloadMinPerTransferBps:    2097152,
			GenericDownloadCircuitThreshold:     3,
			GenericDownloadCircuitOpenMS:        30000,
			GenericDownloadRTPBitrateBps:        8388608,
			GenericDownloadRTPReorderWindow:     512,
			GenericDownloadRTPLossTolerance:     192,
			GenericDownloadRTPGapTimeoutMS:      900,
			InlineResponseHeadroomRatio:         0.15,
			ResponseModePolicy:                  "AUTO(budget_driven_inline_or_rtp)",
		},
		ActiveStrategySummary: ActiveStrategySummary{
			ResponseModePolicy:            "AUTO(budget_driven_inline_or_rtp)",
			LargeResponseDeliveryFamily:   "stream_primary|range_primary|adaptive_segmented_primary|fallback_segmented",
			SegmentedProfileSelector:      "explicit_child>generic-rtp>boundary-rtp>boundary-http>standard-http",
			EntrySelectionPolicy:          "path_clean(dedupe_slash+dot_segment)=>normalized_path; root_or_default_document=>mapped_base; mapped_base/default_document=>mapped_base; mapped_base/*=>suffix_forward",
			UDPControlHeaderPolicy:        "selected_headers(content-type,auth,cookie,validators,range)>oversize_budget_rescue(cookie_trim+content_type_compact+login_validator_drop+bodyless_content_type_drop)>severe_budget_rescue(cookie64_or_auth_only)",
			BoundaryRTPSendProfile:        "boundary-rtp(payload=1200 bitrate_bps=16777216 spacing_us=250 socket_buffer_bytes=16777216 fec=true/8)",
			BoundaryRTPToleranceProfile:   "boundary(reorder=128 loss=48 gap_timeout_ms=300 fec=true/8)",
			PlaybackRTPToleranceProfile:   "range_playback(reorder=192 loss=64 gap_timeout_ms=450 fec=true/8)",
			GenericDownloadRTPSendProfile: "generic-rtp(payload=1200 bitrate_bps=8388608 socket_buffer_bytes=33554432 fec=true/8)",
			GenericDownloadRTPTolerance:   "generic_download(reorder=512 loss=192 gap_timeout_ms=900 fec=true/8)",
			GenericDownloadCircuitPolicy:  "threshold=3 open_ms=30000 severe_media_failure_threshold=1",
			GenericDownloadGuardPolicy:    "generic_download_profile_guard=aligned payload<=1200 bitrate<=8388608 socket_buffer<=33554432 reorder<=512 loss<=192 gap_timeout_ms<=900 fec=true/8",
		},
		UIDeliverySummary: UIDeliverySummary{MetadataPresent: true, ConsistencyStatus: "aligned", ConsistencyDetail: "source, build bundle, embedded ui metadata, and delivery guard are aligned", BuildNonce: "20260322T010203-1234", EmbeddedAt: "2026-03-22 01:02:03", UISourceLatestWrite: "2026-03-22 00:59:59", EmbeddedHashSHA256: "deadbeef", AssetBaseMode: "relative_assets+basepath_meta", RouterBasePathPolicy: "meta_base_path_or_relative_history", DeliveryGuardStatus: "aligned", DeliveryGuardDetail: "no legacy drift detected", DeliveryGuardRemoved: 0, DeliveryGuardRemaining: 0, DeliveryGuardActiveHits: 0},
		ConfigPath:        "./configs/config.yaml",
		ConfigSource:      "env",
		RunMode:           "prod",
		UIMode:            "external",
		UIURL:             "external",
		APIURL:            "http://127.0.0.1:18080/api",
		SIPListen:         ListenEndpoint{IP: "0.0.0.0", Port: 5060, Transport: "TCP"},
		RTPListen:         RTPListen{IP: "0.0.0.0", PortRange: "20000-20100", Transport: "UDP"},
		StorageDirs:       StorageDirs{TempDir: "./data/temp", FinalDir: "./data/final", AuditDir: "./data/audit", LogDir: "./data/logs"},
		BusinessExecution: BusinessExecutionStatus{State: "active", RouteCount: 2, Message: "业务执行层已激活，下游 HTTP 隧道映射可用", Impact: "A 网 HTTP 落地可执行"},
		SelfCheckSummary: SelfCheckSummary{
			GeneratedAt: "2026-01-02T03:04:05Z",
			Overall:     "info",
			Info:        7,
			Warn:        0,
			Error:       0,
		},
	}
	fmt.Println(s.ToLogText())
	// Output:
	// startup summary:
	// - node_id: gateway-a-01
	// - config: path=./configs/config.yaml source=env
	// - run_mode: prod
	// - auto_generated_config: false
	// - ui: mode=external url=external
	// - api_url: http://127.0.0.1:18080/api
	// - session: registration=- heartbeat=- last_register=- last_heartbeat=- next_retry=- failure=-
	// - network_mode: SENDER_SIP_RTP__RECEIVER_SIP_RTP
	// - capability_supported: supports_small_request_body,supports_large_request_body,supports_large_response_body,supports_streaming_response,supports_bidirectional_http_tunnel,supports_transparent_http_proxy
	// - capability_unsupported: -
	// - transport_plan: req_meta=sip_control req_body=sip_or_rtp_auto resp_meta=sip_control resp_body=rtp_stream req_limit=-1 resp_limit=-1
	// - effective_transport: udp_control_max_bytes=1300 udp_catalog_max_bytes=1300 effective_inline_budget_bytes=153 udp_request_parallelism_per_device=4 udp_callback_parallelism_per_peer=4 udp_bulk_parallelism_per_device=4 udp_segment_parallelism_per_device=12 udp_small_request_max_wait_ms=1500 adaptive_playback_hot_window_bytes=4194304 adaptive_playback_segment_cache_bytes=268435456 adaptive_playback_segment_cache_ttl_ms=30000 adaptive_playback_prefetch_segments=2 adaptive_primary_segment_after_failures=2 generic_download_window_bytes=2097152 generic_download_open_ended_window_bytes=8388608 generic_download_segment_concurrency=1 generic_download_total_bitrate_bps=33554432 generic_download_min_per_transfer_bitrate_bps=2097152 generic_download_circuit_failure_threshold=3 generic_download_circuit_open_ms=30000 generic_download_rtp_bitrate_bps=8388608 generic_download_rtp_reorder_window_packets=512 generic_download_rtp_loss_tolerance_packets=192 generic_download_rtp_gap_timeout_ms=900 inline_response_headroom_ratio=0.15 response_mode_policy=AUTO(budget_driven_inline_or_rtp)
	// - active_strategy_snapshot: response_mode_policy=AUTO(budget_driven_inline_or_rtp) large_response_delivery_family=stream_primary|range_primary|adaptive_segmented_primary|fallback_segmented segmented_profile_selector=explicit_child>generic-rtp>boundary-rtp>boundary-http>standard-http entry_selection_policy=path_clean(dedupe_slash+dot_segment)=>normalized_path; root_or_default_document=>mapped_base; mapped_base/default_document=>mapped_base; mapped_base/*=>suffix_forward udp_control_header_policy=selected_headers(content-type,auth,cookie,validators,range)>oversize_budget_rescue(cookie_trim+content_type_compact+login_validator_drop+bodyless_content_type_drop)>severe_budget_rescue(cookie64_or_auth_only) boundary_rtp_send=boundary-rtp(payload=1200 bitrate_bps=16777216 spacing_us=250 socket_buffer_bytes=16777216 fec=true/8) boundary_rtp_tolerance=boundary(reorder=128 loss=48 gap_timeout_ms=300 fec=true/8) playback_rtp_tolerance=range_playback(reorder=192 loss=64 gap_timeout_ms=450 fec=true/8) generic_download_rtp_send=generic-rtp(payload=1200 bitrate_bps=8388608 socket_buffer_bytes=33554432 fec=true/8) generic_download_rtp_tolerance=generic_download(reorder=512 loss=192 gap_timeout_ms=900 fec=true/8) generic_download_circuit=threshold=3 open_ms=30000 severe_media_failure_threshold=1 generic_download_guard=generic_download_profile_guard=aligned payload<=1200 bitrate<=8388608 socket_buffer<=33554432 reorder<=512 loss<=192 gap_timeout_ms<=900 fec=true/8
	// - ui_delivery_consistency: status=aligned detail=source, build bundle, embedded ui metadata, and delivery guard are aligned build_nonce=20260322T010203-1234 embedded_at=2026-03-22 01:02:03 ui_source_latest_write=2026-03-22 00:59:59 embedded_hash=deadbeef asset_base_mode=relative_assets+basepath_meta router_base_path_policy=meta_base_path_or_relative_history delivery_guard_status=aligned delivery_guard_detail=no legacy drift detected delivery_guard_removed=0 delivery_guard_remaining=0 delivery_guard_hits=0 metadata_present=true
	// - sip_listen: ip=0.0.0.0 port=5060 transport=TCP
	// - rtp_listen: ip=0.0.0.0 port_range=20000-20100 transport=UDP
	// - storage_dirs: temp=./data/temp final=./data/final audit=./data/audit log=./data/logs
	// - business_execution: state=active route_count=2 message=业务执行层已激活，下游 HTTP 隧道映射可用 impact=A 网 HTTP 落地可执行
	// - self_check_summary: generated_at=2026-01-02T03:04:05Z overall=info info=7 warn=0 error=0
	// - data_sources: node_config=- peers=- mappings=- mode=- capability=-
}
